baseURL = "https://yuyangyao.com/"
languageCode = "en-us"
title = "Yuyang Yao"

theme = "PaperMod"

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "Home"
url = "/#home"
weight = 10

[[menu.main]]
name = "Research"
url = "/#research"
weight = 20

[[menu.main]]
name = "Publications"
url = "/#publications"
weight = 30

[[menu.main]]
name = "About me"
url = "/#about-me"
weight = 40



[params]
defaultTheme = "auto"
ShowReadingTime = false
ShowShareButtons = false
ShowCodeCopyButtons = true

[params.profileMode]
enabled = false
title = "Yuyang Yao"
subtitle = """
Cognitive Science of Language | Computational Modelling | Language Models
"""

[[params.profileMode.buttons]]
name = "Research"
url = "/research/"

[[params.profileMode.buttons]]
name = "CV"
url = "/yao_CV.pdf"
